EventConsumerFn:
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: !Sub '${AWS::StackName}-event-consumer'
    Handler: sam_example_app/event_consumer_lambda.handler
    Events:
      HttpApiEvent:
        Type: HttpApi
        Properties:
          Path: /{proxy+}
          Method: ANY
          ApiId: !Ref ConsumerHttpApi
EventConsumerLogGroup:
  Type: AWS::Logs::LogGroup
  DependsOn:
    - EventConsumerFn
  Properties:
    LogGroupName: !Sub '/aws/lambda/${AWS::StackName}-event-consumer'
    RetentionInDays: 3
