EventConsumerFn:
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: !Sub '${AWS::StackName}-event-consumer'
    Handler: sam_example_app/event_consumer_lambda.handler
    Events:
      ApiEvent:
        Type: Api
        Properties:
          Path: /consumer-events
          Method: POST
          RestApiId: !Ref SamManagedApi
EventConsumerLogGroup:
  Type: AWS::Logs::LogGroup
  DependsOn:
    - EventConsumerFn
  Properties:
    LogGroupName: !Sub '/aws/lambda/${AWS::StackName}-event-consumer'
    RetentionInDays: 3
