S3EventErrorHandlerFn:
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: !Sub '${AWS::StackName}-s3-event-error-handler'
    Handler: s3_event_error_handler_lambda.handler
    Policies:
      - S3CrudPolicy:
          BucketName: '{{ env("USER").lower() }}-sam-events'
      - LambdaInvokePolicy:
          FunctionName: !Sub '${AWS::StackName}-s3-event-handler'
      - DynamoDBCrudPolicy:
          TableName: !Ref EventLogTable
S3EventErrorHandlerLogGroup:
  Type: AWS::Logs::LogGroup
  DependsOn:
    - S3EventErrorHandlerFn
  Properties:
    LogGroupName: !Sub '/aws/lambda/${AWS::StackName}-s3-event-error-handler'
    RetentionInDays: 3
