{% from "sam/macro/util.j2" import include with context %}

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM example application

Parameters:
  {{ include("parameters.yaml") | indent(2) }}

Globals:
  {{ include("globals.yaml") | indent(2) }}

Resources:
  {{ include("buckets.yaml") | indent(2) }}
  {{ include("tables.yaml") | indent(2) }}
   # note: only the first Api in the template will be exposed by 'sam local start-api'
  {{ include("api-gateway.yaml") | indent(2) }}
  {{ include("event-consumer.yaml") | indent(2) }}
  {{ include("event-API-async-invoke.yaml") | indent(2) }}

  # REST API gateway with S3 integration
  {{ include("event-API-s3.yaml") | indent(2) }}
  {{ include("s3-event-error-handler.yaml") | indent(2) }}


Outputs:
  ConsumerHttpApiUrl:
    Value: !Sub "https://${ConsumerHttpApi}.execute-api.${AWS::Region}.amazonaws.com/${stage}"
  S3EventApiUrl:
    Value: !Sub "https://${S3EventApi}.execute-api.${AWS::Region}.amazonaws.com/${stage}"
  AsyncInvokeApiUrl:
    Value: !Sub "https://${AsyncInvokeApi}.execute-api.${AWS::Region}.amazonaws.com/${stage}"
